package com.android.sample.feature.rewards

import com.android.sample.data.UserProfile

/**
 * Pure function style reward engine.
 *
 * It looks at the old and new profile, figures out which new levels have been reached, applies the
 * configured rewards, and returns:
 * - the updated profile (with coins/stats/accessories changed)
 * - a summary of what was granted (for UI feedback).
 *
 * Some parts of this code have been generated by AI.
 */
class LevelRewardEngine(private val config: LevelRewardConfig = LevelRewardConfig) {

  data class Result(val updatedProfile: UserProfile, val summary: GrantedRewardsSummary)

  fun applyLevelUpRewards(oldProfile: UserProfile, newProfile: UserProfile): Result {
    // no level increase → nothing to do
    if (newProfile.level <= oldProfile.level) {
      return Result(newProfile, GrantedRewardsSummary())
    }

    // Track which levels we have already rewarded; for users migrating from old version,
    // lastRewardedLevel defaults to 0 so all existing levels will be rewarded once.
    val alreadyRewardedUpTo = oldProfile.lastRewardedLevel

    // Levels that are now reached and not yet rewarded
    val newlyRewardedLevels =
        (alreadyRewardedUpTo + 1..newProfile.level)
            .filter { it > 0 } // ignore invalid
            .toList()
    if (newlyRewardedLevels.isEmpty()) {
      return Result(newProfile, GrantedRewardsSummary())
    }

    var profile = newProfile
    var totalCoins = 0
    val accessoriesGranted = mutableListOf<String>()
    var extraPoints = 0

    newlyRewardedLevels.forEach { level ->
      val reward = config.rewardForLevel(level) ?: return@forEach
      if (reward.coins != 0) {
        profile = profile.copy(coins = profile.coins + reward.coins)
        totalCoins += reward.coins
      }
      if (reward.extraPoints != 0) {
        profile = profile.copy(points = profile.points + reward.extraPoints)
        extraPoints += reward.extraPoints
      }

      if (reward.accessoryIds.isNotEmpty()) {
        // Accessories list is just a list of "slot:id" strings.
        // Here we just add them if not already present.
        val newAccessories =
            reward.accessoryIds.filterNot { rewardId ->
              profile.accessories.any { it.endsWith(":$rewardId") || it == rewardId }
            }

        if (newAccessories.isNotEmpty()) {
          profile = profile.copy(accessories = profile.accessories + newAccessories)
          accessoriesGranted.addAll(newAccessories)
        }
      }
    }

    val finalProfile =
        profile.copy(
            // Mark up to which level rewards have been fully processed
            lastRewardedLevel = newProfile.level)

    val summary =
        GrantedRewardsSummary(
            rewardedLevels = newlyRewardedLevels,
            coinsGranted = totalCoins,
            accessoryIdsGranted = accessoriesGranted,
            extraPointsGranted = extraPoints)

    return Result(finalProfile, summary)
  }
}
