package com.android.sample.ui.flashcards

import androidx.activity.ComponentActivity
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.hasContentDescription
import androidx.compose.ui.test.hasText
import androidx.compose.ui.test.junit4.AndroidComposeTestRule
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.android.sample.ui.flashcards.data.FirestoreFlashcardsRepoProvider
import com.android.sample.ui.flashcards.model.Deck
import com.android.sample.ui.flashcards.model.Flashcard
import com.android.sample.ui.theme.EduMonTheme
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.tasks.await
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Flashcards UI flow that does NOT touch MainActivity. It hosts FlashcardsApp directly and
 * pre-populates the repo to avoid performTextInput (works around Semantics getIsEditable crash).
 * Parts of this code have been generated by AI.
 */
@RunWith(AndroidJUnit4::class)
class FlashcardsFlowTest {

  @get:Rule val composeRule = createAndroidComposeRule<ComponentActivity>()

  // tiny helpers
  private fun AndroidComposeTestRule<*, *>.waitAndAssertVisible(
      text: String,
      timeoutMs: Long = 10_000
  ) {
    val m = hasText(text, substring = true, ignoreCase = true)
    waitUntil(timeoutMs) {
      onAllNodes(m, useUnmergedTree = true).fetchSemanticsNodes().isNotEmpty()
    }
    onNode(m, useUnmergedTree = true).assertIsDisplayed()
  }

  @Test
  fun studyFlow_withPrepopulatedDeck_navigatesAndShowsContent() {
    val repo = FirestoreFlashcardsRepoProvider.get()

    runBlocking { com.google.firebase.auth.FirebaseAuth.getInstance().signInAnonymously().await() }

    runBlocking {
      repo.createDeck(
          title = "CI Deck",
          description = "Preloaded",
          cards = listOf(Flashcard(question = "What is binary search?", answer = "O(log n)")))
    }

    composeRule.setContent { EduMonTheme { FlashcardsApp() } }

    val studyMatcher = hasText("Study", substring = true, ignoreCase = true)

    composeRule.waitUntil(10_000) {
      composeRule
          .onAllNodes(studyMatcher, useUnmergedTree = true)
          .fetchSemanticsNodes()
          .isNotEmpty()
    }

    val study = composeRule.onAllNodes(studyMatcher, useUnmergedTree = true)[0]
    study.performClick()

    composeRule.waitAndAssertVisible("Card 1") // matches "Card 1 of 1" etc.
    composeRule.waitAndAssertVisible("Question")
    composeRule.waitAndAssertVisible("reveal answer") // matches "Tap to reveal answer"
  }

  @Test
  fun deleteDialog_shows_onTrashClick_andCallsCallback_onConfirm() {
    // Arrange a sample deck and a capture var for the callback
    val deck =
        Deck(
            id = "deck-1",
            title = "Algebra",
            description = "Basics",
            cards = mutableListOf(Flashcard(question = "Q1", answer = "A1")))
    var deletedId: String? = null

    composeRule.setContent {
      EduMonTheme {
        // Render only the row to keep the test tight
        com.android.sample.ui.flashcards.DeckRow(
            deck = deck,
            onStudyDeck = { /* no-op */},
            onDeleteDeck = { id -> deletedId = id } // <- we assert this fires
            )
      }
    }

    // The dialog is not visible initially
    composeRule.onNodeWithText("Delete deck?").assertDoesNotExist()

    // Click the trash icon -> dialog appears
    composeRule.onNode(hasContentDescription("Delete deck")).performClick()
    composeRule.onNodeWithText("Delete deck?").assertIsDisplayed()
    composeRule
        .onNodeWithText("This will permanently remove “${deck.title}” and its cards.")
        .assertIsDisplayed()

    // Cancel first -> no callback, dialog closes
    composeRule.onNodeWithText("Cancel").performClick()
    composeRule.onNodeWithText("Delete deck?").assertDoesNotExist()
    assert(deletedId == null)

    // Open again and confirm
    composeRule.onNode(hasContentDescription("Delete deck")).performClick()
    composeRule.onNodeWithText("Delete").performClick()

    // Assert callback fired with the right id and dialog dismissed
    assert(deletedId == deck.id)
    composeRule.onNodeWithText("Delete deck?").assertDoesNotExist()
  }
}
