package com.android.sample.ui.flashcards

import android.content.Context
import androidx.activity.ComponentActivity
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.hasContentDescription
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import androidx.compose.ui.test.onAllNodesWithText
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.android.sample.ui.flashcards.data.FlashcardsRepositoryProvider
import com.android.sample.ui.flashcards.model.Deck
import com.android.sample.ui.flashcards.model.Flashcard
import com.android.sample.ui.theme.EduMonTheme
import kotlinx.coroutines.runBlocking
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Flashcards UI flow that does NOT touch MainActivity. It hosts FlashcardsApp directly and
 * pre-populates the repo to avoid performTextInput (works around Semantics getIsEditable crash).
 * Parts of this code have been generated by AI.
 */
@RunWith(AndroidJUnit4::class)
class FlashcardsFlowTest {

  @get:Rule val composeRule = createAndroidComposeRule<ComponentActivity>()

  @Before
  fun setUp() {
    val ctx = ApplicationProvider.getApplicationContext<Context>()
    FlashcardsRepositoryProvider.init(ctx)

    // optional: clear DataStore between tests
    // runBlocking { clearFlashcardsStore(ctx) }
  }

  @Test
  fun studyFlow_withPrepopulatedDeck_navigatesAndShowsContent() {
    // Seed the SAME repo the app uses
    val repo = FlashcardsRepositoryProvider.repository
    runBlocking {
      repo.createDeck(
          title = "CI Deck",
          description = "Preloaded",
          cards = listOf(Flashcard(question = "What is binary search?", answer = "O(log n)")))
    }

    composeRule.setContent { EduMonTheme { FlashcardsApp() } }

    composeRule.onNodeWithText("Flashcards").assertIsDisplayed()

    // Wait for at least one Study button, then click the first
    val studyNodes = composeRule.onAllNodesWithText("Study")
    composeRule.waitUntil(3_000) { studyNodes.fetchSemanticsNodes().isNotEmpty() }
    studyNodes[0].performClick()

    composeRule.onNodeWithText("Card 1 of 1").assertIsDisplayed()
    composeRule.onNodeWithText("Question").assertIsDisplayed()
    composeRule.onNodeWithText("Tap to reveal answer").assertIsDisplayed()

    composeRule.onNodeWithText("Reveal").performClick()
    composeRule.onNodeWithText("Answer").assertIsDisplayed()
    composeRule.onNodeWithText("Medium").performClick()

    composeRule.onNodeWithText("← Back").performClick()
    composeRule.onNodeWithText("Flashcards").assertIsDisplayed()
  }

  @Test
  fun deleteDialog_shows_onTrashClick_andCallsCallback_onConfirm() {
    // Arrange a sample deck and a capture var for the callback
    val deck =
        Deck(
            id = "deck-1",
            title = "Algebra",
            description = "Basics",
            cards = mutableListOf(Flashcard(question = "Q1", answer = "A1")))
    var deletedId: String? = null

    composeRule.setContent {
      EduMonTheme {
        // Render only the row to keep the test tight
        com.android.sample.ui.flashcards.DeckRow(
            deck = deck,
            onStudyDeck = { /* no-op */},
            onDeleteDeck = { id -> deletedId = id } // <- we assert this fires
            )
      }
    }

    // The dialog is not visible initially
    composeRule.onNodeWithText("Delete deck?").assertDoesNotExist()

    // Click the trash icon -> dialog appears
    composeRule.onNode(hasContentDescription("Delete deck")).performClick()
    composeRule.onNodeWithText("Delete deck?").assertIsDisplayed()
    composeRule
        .onNodeWithText("This will permanently remove “${deck.title}” and its cards.")
        .assertIsDisplayed()

    // Cancel first -> no callback, dialog closes
    composeRule.onNodeWithText("Cancel").performClick()
    composeRule.onNodeWithText("Delete deck?").assertDoesNotExist()
    assert(deletedId == null)

    // Open again and confirm
    composeRule.onNode(hasContentDescription("Delete deck")).performClick()
    composeRule.onNodeWithText("Delete").performClick()

    // Assert callback fired with the right id and dialog dismissed
    assert(deletedId == deck.id)
    composeRule.onNodeWithText("Delete deck?").assertDoesNotExist()
  }
}
