package com.android.sample.ui.flashcards.data

import android.annotation.SuppressLint
import android.content.Context

/** Simple provider for FlashcardsRepo function getAppContextSafely was generated by an AI */
object FlashcardsRepositoryProvider {

  @Volatile private var repo: FlashcardsRepository? = null

  // Self-initializing lazy getter — no explicit init() needed
  val repository: FlashcardsRepository
    get() {
      return repo
          ?: synchronized(this) {
            repo
                ?: run {
                  val appContext = getAppContextSafely()
                  val storage = FlashcardsStorage(appContext)
                  val newRepo = DataStoreFlashcardsRepository(storage)
                  repo = newRepo
                  newRepo
                }
          }
    }

  @SuppressLint("PrivateApi")
  private fun getAppContextSafely(): Context {
    // Try to fetch the Application context reflectively
    return try {
      val activityThread = Class.forName("android.app.ActivityThread")
      val app = activityThread.getMethod("currentApplication").invoke(null) as Context
      app.applicationContext
    } catch (e: Exception) {
      throw IllegalStateException(
          "FlashcardsRepositoryProvider: cannot obtain Application context automatically; " +
              "if this fails, you may need to call init(context) manually in Application.onCreate().",
          e)
    }
  }
}
