package com.android.sample.ui.flashcards.data

import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.lifecycle.viewmodel.initializer
import androidx.lifecycle.viewmodel.viewModelFactory
import com.android.sample.ui.flashcards.StudyViewModel
import com.android.sample.ui.flashcards.model.Confidence
import com.android.sample.ui.theme.*

// Some parts of this code have been generated by AI.
@Composable
fun StudyScreen(deckId: String, onBack: () -> Unit) {
  // Pass deckId to VM.
  // Uses primary constructor which includes default Repositories and requireAuth=true.
  val vm: StudyViewModel =
      viewModel(factory = viewModelFactory { initializer { StudyViewModel(deckId) } })

  // Nullable while first value loads
  val s by vm.state.collectAsState(initial = null)

  Column(Modifier.fillMaxSize().background(BackgroundDark).padding(16.dp)) {
    // Top bar
    TextButton(
        onClick = onBack, colors = ButtonDefaults.textButtonColors(contentColor = TextLight)) {
          Text("← Back")
        }

    Spacer(Modifier.height(8.dp))

    // ------- ONE stable Column body; choose a branch without early returns -------
    when {
      // Loading
      s == null -> {
        Spacer(Modifier.height(24.dp))
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
          CircularProgressIndicator(color = AccentViolet)
        }
        // Fill remaining space so Column children count stays predictable
        Spacer(Modifier.weight(1f))
      }

      // If your VM exposes an error string, show it here (optional, else remove branch)

      // Empty deck
      s!!.total == 0 -> {
        Spacer(Modifier.height(24.dp))
        Text(
            "This deck has no cards yet.",
            color = TextLight,
            style = MaterialTheme.typography.titleMedium)
        Text("Add some cards, then come back to study.", color = TextLight.copy(alpha = .7f))
        Spacer(Modifier.weight(1f))
      }

      // Main content
      else -> {
        val state = s!!
        val deck = state.deck
        Text(
            deck?.title ?: "Untitled Deck",
            style = MaterialTheme.typography.headlineMedium,
            color = AccentMagenta)
        Text("Card ${state.index + 1} of ${state.total}", color = TextLight.copy(alpha = .7f))

        Spacer(Modifier.height(16.dp))

        FlipCard(
            front = { QuestionSide(text = state.currentOrNull?.question ?: "No question") },
            back = { AnswerSide(text = state.currentOrNull?.answer ?: "No answer") },
            flipped = state.showingAnswer,
            onToggle = vm::flip,
            modifier = Modifier.weight(1f).fillMaxWidth())

        Spacer(Modifier.height(16.dp))
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
          OutlinedButton(
              onClick = vm::prev,
              enabled = !state.isFirst,
              colors = ButtonDefaults.outlinedButtonColors(contentColor = TextLight)) {
                Text("Previous")
              }

          OutlinedButton(
              onClick = vm::flip,
              colors = ButtonDefaults.outlinedButtonColors(contentColor = TextLight)) {
                Text(if (state.showingAnswer) "Hide" else "Reveal")
              }

          Button(
              onClick = vm::next,
              enabled = !state.isLast,
              colors =
                  ButtonDefaults.buttonColors(
                      containerColor = AccentViolet, contentColor = TextLight)) {
                Text("Next")
              }
        }

        if (state.showingAnswer) {
          Spacer(Modifier.height(12.dp))
          Text("How confident were you?", color = TextLight.copy(alpha = .8f))
          Spacer(Modifier.height(8.dp))
          Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            Button(
                onClick = { vm.record(Confidence.LOW) },
                modifier = Modifier.weight(1f),
                colors =
                    ButtonDefaults.buttonColors(
                        containerColor = AccentMagenta, contentColor = TextLight)) {
                  Text("Low")
                }

            Button(
                onClick = { vm.record(Confidence.MEDIUM) },
                modifier = Modifier.weight(1f),
                colors =
                    ButtonDefaults.buttonColors(
                        containerColor = AccentViolet, contentColor = TextLight)) {
                  Text("Medium")
                }

            Button(
                onClick = { vm.record(Confidence.HIGH) },
                modifier = Modifier.weight(1f),
                colors =
                    ButtonDefaults.buttonColors(
                        containerColor = AccentMint, contentColor = TextLight)) {
                  Text("High")
                }
          }
        } else {
          Spacer(Modifier.height(12.dp))
          Text("Tap “Reveal” to view the answer", color = TextLight.copy(alpha = .6f))
        }
      }
    }
  }
}

@Composable private fun QuestionSide(text: String) = CenterCard(title = "Question", body = text)

@Composable private fun AnswerSide(text: String) = CenterCard(title = "Answer", body = text)

@Composable
private fun CenterCard(title: String, body: String) {
  Surface(
      color = MidDarkCard,
      contentColor = TextLight,
      tonalElevation = 3.dp,
      shape = MaterialTheme.shapes.extraLarge,
      modifier = Modifier.fillMaxSize()) {
        Column(
            Modifier.fillMaxSize().padding(20.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center) {
              Text(title, style = MaterialTheme.typography.titleMedium, color = AccentViolet)
              Spacer(Modifier.height(8.dp))
              Text(
                  body,
                  style = MaterialTheme.typography.headlineSmall,
                  color = TextLight,
                  textAlign = TextAlign.Center)
              Spacer(Modifier.height(8.dp))
              Text("Tap to reveal answer", color = TextLight.copy(alpha = .6f))
            }
      }
}

/** Simple 3D flip using rotationY. */
@Composable
private fun FlipCard(
    front: @Composable () -> Unit,
    back: @Composable () -> Unit,
    flipped: Boolean,
    onToggle: () -> Unit,
    modifier: Modifier = Modifier
) {
  val rotation by animateFloatAsState(if (flipped) 180f else 0f, label = "flip")
  val cameraDistance = 12_000f

  Box(
      modifier
          .graphicsLayer {
            this.cameraDistance = cameraDistance
            rotationY = rotation
          }
          .clickable { onToggle() }) {
        if (rotation <= 90f) {
          Box(Modifier.graphicsLayer { rotationY = 0f }) { front() }
        } else {
          Box(Modifier.graphicsLayer { rotationY = 180f }) { back() }
        }
      }
}
