package com.android.sample.ui.todo

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.android.sample.data.Priority
import com.android.sample.data.Status
import com.android.sample.data.ToDo
import com.android.sample.repositories.ToDoRepository
import com.android.sample.ui.location.Location
import com.android.sample.ui.location.LocationRepository
import com.android.sample.ui.location.NominatimLocationRepository
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import java.time.LocalDate
import kotlinx.coroutines.launch
import okhttp3.OkHttpClient

/**
 * ViewModel responsible for managing the UI state and logic of the Add To-Do screen. Some parts of
 * this code have been generated by AI.
 */
class AddToDoViewModel(
    private val repo: ToDoRepository,
    private val locationRepo: LocationRepository = NominatimLocationRepository(OkHttpClient()),
) : ViewModel() {

  // Required fields
  var title by mutableStateOf("") // user-entered title text
  var dueDate by mutableStateOf(LocalDate.now()) // default to today
  var priority by mutableStateOf(Priority.MEDIUM) // default to medium priority
  var status by mutableStateOf(Status.TODO) // default status

  // Optional fields
  //var location by mutableStateOf<String?>(null) // optional location text
    /** What the user typed in the location field. */
    var locationQuery by mutableStateOf("")

    /** Suggestions coming from Nominatim. */
    var locationSuggestions by mutableStateOf<List<Location>>(emptyList())

    /** Currently selected location (if any). */
    private var selectedLocation: Location? = null

    // Also keep a plain string to save into ToDo (for backwards compatibility)
    private var locationString: String? = null

    // Debounce job so we don’t spam Nominatim on each keystroke
    private var locationSearchJob: Job? = null
  var linksText by mutableStateOf("") // comma-separated links
  var note by mutableStateOf<String?>(null) // optional note/description
  var notificationsEnabled by mutableStateOf(false) // switch for notifications

  // Validation rule: can only save if title is not blank
  val canSave
    get() = title.isNotBlank()

    // Called by the UI when the location text changes
    fun onLocationQueryChange(query: String) {
        locationQuery = query
        selectedLocation = null
        locationString = query.ifBlank { null }

        // Cancel any ongoing search
        locationSearchJob?.cancel()

        if (query.length < 3) {
            // too short: clear suggestions
            locationSuggestions = emptyList()
            return
        }

        locationSearchJob =
            viewModelScope.launch {
                // small debounce
                delay(300)
                val results =
                    try {
                        locationRepo.search(query)
                    } catch (e: Exception) {
                        emptyList()
                    }
                locationSuggestions = results
            }
    }

    // Called by the UI when the user picks a suggestion
    fun onLocationSelected(location: Location) {
        selectedLocation = location
        locationString = location.name
        locationQuery = location.name
        locationSuggestions = emptyList()
    }
  /**
   * Called when the user presses "Save".
   * - Validates input
   * - Builds a ToDo object
   * - Saves it via the repository
   * - Then triggers onDone()
   */
  fun save(onDone: () -> Unit) =
      viewModelScope.launch {
          if (!canSave) return@launch

          val links = linksText.split(",").map { it.trim() }.filter { it.isNotBlank() }

          val finalLocation =
              (selectedLocation?.name ?: locationString)?.takeIf { it.isNotBlank() }

          repo.add(
              ToDo(
                  title = title.trim(),
                  dueDate = dueDate,
                  priority = priority,
                  status = status,
                  location = finalLocation,
                  links = links,
                  note = note?.takeIf { it.isNullOrBlank().not() },
                  notificationsEnabled = notificationsEnabled))

          onDone()
      }

}
