package com.android.sample.ui.todo

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.android.sample.data.Status
import com.android.sample.data.ToDo
import com.android.sample.repositories.ToDoRepository
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

// UI model for the Overview screen
// Some parts of this code have been generated by AI.
data class OverviewUiState(val items: List<ToDo> = emptyList())

/** ViewModel for the Overview screen. */
class OverviewViewModel(private val repo: ToDoRepository) : ViewModel() {

  val uiState: StateFlow<OverviewUiState> =
      repo.todos
          .map { list ->
            // Sort: items with DONE last; among the rest, nearest due date first
            val sorted =
                list.sortedWith(
                    compareBy<ToDo> { it.status == Status.DONE }
                        .thenBy { it.dueDate } // earlier dates first
                    )
            OverviewUiState(sorted)
          }
          .stateIn(
              scope = viewModelScope,
              started = SharingStarted.WhileSubscribed(5_000),
              initialValue = OverviewUiState() // initial UI state (empty list)
              )

  // Cycle status in order: TODO → IN_PROGRESS → DONE → TODO
  fun cycleStatus(id: String) =
      viewModelScope.launch {
        repo.getById(id)?.let {
          val next =
              when (it.status) {
                Status.TODO -> Status.IN_PROGRESS
                Status.IN_PROGRESS -> Status.DONE
                Status.DONE -> Status.TODO
              }
          repo.update(it.copy(status = next))
        }
      }

  // Delete an item by id
  fun delete(id: String) = viewModelScope.launch { repo.remove(id) }
}
