package com.android.sample.ui.flashcards.data

import com.android.sample.ui.flashcards.model.Deck
import com.android.sample.ui.flashcards.model.Flashcard
import java.lang.reflect.Field
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.*
import org.junit.Test

// Some parts of this code have been generated by an AI.
class InMemoryFlashcardsRepositoryTest {

  /** Reset the repository after each test so they don't interfere with each other. */
  @After
  fun tearDown() {
    val decksField: Field = InMemoryFlashcardsRepository::class.java.getDeclaredField("_decks")
    decksField.isAccessible = true
    decksField.set(InMemoryFlashcardsRepository, MutableStateFlow<List<Deck>>(emptyList()))
  }

  @Test
  fun deck_returns_correct_deck_when_ID_exists() = runTest {
    // Arrange
    val deckId = InMemoryFlashcardsRepository.createDeck("Science", "Biology", emptyList())

    // Act
    val foundDeck = InMemoryFlashcardsRepository.deck(deckId)

    // Assert
    assertNotNull(foundDeck)
    assertEquals(deckId, foundDeck!!.id)
    assertEquals("Science", foundDeck.title)
  }

  @Test
  fun deck_returns_null_when_ID_does_not_exist() = runTest {
    // Arrange
    InMemoryFlashcardsRepository.createDeck("History", "WW2", emptyList())

    // Act
    val foundDeck = InMemoryFlashcardsRepository.deck("non-existent-id")

    // Assert
    assertNull(foundDeck)
  }

  @Test
  fun addCard_successfully_adds_a_card_to_the_specified_deck() = runTest {
    // Arrange
    val initialCard = Flashcard(id = "card-101", question = "Q1", answer = "A1")
    val deckId = InMemoryFlashcardsRepository.createDeck("Math", "Algebra", listOf(initialCard))

    // Act
    val newCard = Flashcard(id = "card-102", question = "Q2", answer = "A2")
    InMemoryFlashcardsRepository.addCard(deckId, newCard)
    val updatedDeck = InMemoryFlashcardsRepository.deck(deckId)

    // Assert
    assertNotNull(updatedDeck)
    assertEquals(2, updatedDeck!!.cards.size)
    assertEquals(initialCard, updatedDeck.cards[0])
    assertEquals(newCard, updatedDeck.cards[1])
  }

  @Test
  fun addCard_does_not_change_anything_if_deck_ID_is_invalid() = runTest {
    // Arrange
    val deckId = InMemoryFlashcardsRepository.createDeck("Geography", "Countries", emptyList())
    val initialDecksState = InMemoryFlashcardsRepository.decks.value.toList()

    // Act
    InMemoryFlashcardsRepository.addCard(
        "invalid-id", Flashcard(id = "card-temp", question = "Question", answer = "Answer"))
    val finalDecksState = InMemoryFlashcardsRepository.decks.value.toList()

    // Assert
    assertEquals(initialDecksState, finalDecksState)
    assertTrue(InMemoryFlashcardsRepository.deck(deckId)!!.cards.isEmpty())
  }
}
