package com.android.sample.ui.todo

import com.android.sample.data.Priority
import com.android.sample.data.Status
import com.android.sample.data.ToDo
import com.android.sample.repositories.ToDoRepositoryLocal
import com.android.sample.ui.location.Location
import com.android.sample.ui.location.LocationRepository
import java.time.LocalDate
import junit.framework.TestCase.assertEquals
import junit.framework.TestCase.assertFalse
import junit.framework.TestCase.assertNull
import junit.framework.TestCase.assertTrue
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.TestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.*

// Some parts of this code have been generated by AI.

/** Fake LocationRepository for testing without network calls */
class FakeLocationRepository : LocationRepository {
  var searchResults = listOf<Location>()
  var searchThrowsException = false

  override suspend fun search(query: String): List<Location> {
    if (searchThrowsException) throw Exception("Network error")
    return searchResults.filter { it.name.contains(query, ignoreCase = true) }
  }
}

@OptIn(ExperimentalCoroutinesApi::class)
class ViewModelsSingleTest {

  private val testDispatcher: TestDispatcher = StandardTestDispatcher()

  @Before
  fun setUp() {
    Dispatchers.setMain(testDispatcher)
  }

  @After
  fun tearDown() {
    Dispatchers.resetMain()
  }

  // ==================== AddToDoViewModel Tests ====================

  @Test
  fun add_canSave_and_save_builds_trimmed_and_calls_onDone() = runTest {
    val repo = ToDoRepositoryLocal()
    val vm = AddToDoViewModel(repo)

    // If blank title, cannot save
    vm.title = "  "
    assertFalse(vm.canSave)

    vm.title = "Hello"
    vm.dueDate = LocalDate.of(2025, 12, 31)
    vm.priority = Priority.HIGH
    vm.status = Status.IN_PROGRESS

    // Set location via the new location API
    vm.onLocationSelected(Location(latitude = 0.0, longitude = 0.0, name = "Office"))

    vm.linksText = "https://a , , https://b ,"
    vm.note = "note"
    vm.notificationsEnabled = true

    var done = false
    vm.save { done = true }
    advanceUntilIdle()

    val saved = repo.todos.first { it.isNotEmpty() }.single()
    assertTrue(done)
    assertEquals("Hello", saved.title)
    assertEquals(LocalDate.of(2025, 12, 31), saved.dueDate)
    assertEquals(Priority.HIGH, saved.priority)
    assertEquals(Status.IN_PROGRESS, saved.status)
    assertEquals("Office", saved.location)
    assertEquals(listOf("https://a", "https://b"), saved.links)
    assertEquals("note", saved.note)
    assertTrue(saved.notificationsEnabled)
  }

  @Test
  fun add_blank_optional_fields_are_omitted() = runTest {
    val repo = ToDoRepositoryLocal()
    val vm = AddToDoViewModel(repo)

    vm.title = "X"

    // Simulate user typing only spaces in location → should be treated as null
    vm.onLocationQueryChange(" ")

    vm.note = ""
    vm.linksText = " , "
    vm.save {}
    advanceUntilIdle()

    val saved = repo.todos.first { it.isNotEmpty() }.single()
    assertNull(saved.location)
    assertNull(saved.note)
    assertTrue(saved.links.isEmpty())
  }

  @Test
  fun add_locationQueryChange_triggersSearch_whenQueryLongEnough() = runTest {
    val repo = ToDoRepositoryLocal()
    val fakeLocationRepo =
        FakeLocationRepository().apply {
          searchResults =
              listOf(
                  Location(46.52, 6.56, "EPFL BC Building"),
                  Location(46.51, 6.55, "EPFL Rolex Center"))
        }
    val vm = AddToDoViewModel(repo, fakeLocationRepo)

    // Short query (less than 2 chars): no suggestions
    vm.onLocationQueryChange("E")
    advanceUntilIdle()
    assertTrue(vm.locationSuggestions.isEmpty())

    // Longer query (2+ chars): triggers search
    vm.onLocationQueryChange("EPFL")
    advanceUntilIdle()
    assertEquals(2, vm.locationSuggestions.size)
    assertEquals("EPFL BC Building", vm.locationSuggestions[0].name)
  }

  @Test
  fun add_locationQueryChange_clearsSelectedLocation() = runTest {
    val repo = ToDoRepositoryLocal()
    val fakeLocationRepo = FakeLocationRepository()
    val vm = AddToDoViewModel(repo, fakeLocationRepo)

    // Select a location first
    val location = Location(46.52, 6.56, "Office")
    vm.onLocationSelected(location)
    assertEquals("Office", vm.locationQuery)

    // Changing query should clear the selected location
    vm.onLocationQueryChange("New Query")
    advanceUntilIdle()

    // Now save and verify location is from the new query, not the old selection
    vm.title = "Task"
    vm.save {}
    advanceUntilIdle()

    val saved = repo.todos.first { it.isNotEmpty() }.single()
    assertEquals("New Query", saved.location)
  }

  @Test
  fun add_locationSelected_setsQueryAndClearsSuggestions() = runTest {
    val repo = ToDoRepositoryLocal()
    val fakeLocationRepo =
        FakeLocationRepository().apply { searchResults = listOf(Location(46.52, 6.56, "EPFL")) }
    val vm = AddToDoViewModel(repo, fakeLocationRepo)

    vm.onLocationQueryChange("EPFL")
    advanceUntilIdle()
    assertTrue(vm.locationSuggestions.isNotEmpty())

    // Select location
    val selected = vm.locationSuggestions[0]
    vm.onLocationSelected(selected)

    assertEquals("EPFL", vm.locationQuery)
    assertTrue(vm.locationSuggestions.isEmpty())
  }

  @Test
  fun add_locationSearch_handlesNetworkError() = runTest {
    val repo = ToDoRepositoryLocal()
    val fakeLocationRepo = FakeLocationRepository().apply { searchThrowsException = true }
    val vm = AddToDoViewModel(repo, fakeLocationRepo)

    vm.onLocationQueryChange("EPFL")
    advanceUntilIdle()

    // Should have empty suggestions on error (no crash)
    assertTrue(vm.locationSuggestions.isEmpty())
  }

  @Test
  fun add_save_usesSelectedLocationName() = runTest {
    val repo = ToDoRepositoryLocal()
    val vm = AddToDoViewModel(repo)

    vm.title = "Meeting"
    val location = Location(46.52, 6.56, "EPFL Rolex Center")
    vm.onLocationSelected(location)

    vm.save {}
    advanceUntilIdle()

    val saved = repo.todos.first { it.isNotEmpty() }.single()
    assertEquals("EPFL Rolex Center", saved.location)
  }

  @Test
  fun add_save_usesQueryString_whenNoLocationSelected() = runTest {
    val repo = ToDoRepositoryLocal()
    val vm = AddToDoViewModel(repo)

    vm.title = "Task"
    vm.onLocationQueryChange("Custom Location")
    advanceUntilIdle()

    vm.save {}
    advanceUntilIdle()

    val saved = repo.todos.first { it.isNotEmpty() }.single()
    assertEquals("Custom Location", saved.location)
  }

  // ==================== EditToDoViewModel Tests ====================

  @Test
  fun edit_init_loads_existing_and_save_updates_with_trimming() = runTest {
    val repo = ToDoRepositoryLocal()
    val id = "todo-1"
    val original =
        ToDo(
            id = id,
            title = "Old",
            dueDate = LocalDate.of(2025, 1, 1),
            priority = Priority.LOW,
            status = Status.TODO,
            location = "Place",
            links = listOf("x"),
            note = "N",
            notificationsEnabled = false)
    repo.add(original)

    val vm = EditToDoViewModel(repo, id)
    advanceUntilIdle()

    // Loaded into fields
    assertEquals("Old", vm.title)
    assertEquals("x", vm.linksText.trim())
    // location is now represented as locationQuery
    assertEquals("Place", vm.locationQuery)

    // Update
    vm.title = "  New  "
    vm.linksText = " a ,  , b "

    // Clear location using the new API (blank → null)
    vm.onLocationQueryChange(" ")

    vm.note = "" // -> null
    vm.status = Status.DONE
    vm.priority = Priority.HIGH

    var done = false
    vm.save { done = true }
    advanceUntilIdle()

    val updated = repo.getById(id)!!
    assertEquals("New", updated.title)
    assertEquals(listOf("a", "b"), updated.links)
    assertNull(updated.location)
    assertNull(updated.note)
    assertEquals(Status.DONE, updated.status)
    assertEquals(Priority.HIGH, updated.priority)
    assertTrue(done)
  }

  @Test
  fun edit_canSave_is_false_when_title_blank() {
    val vm = EditToDoViewModel(ToDoRepositoryLocal(), "missing-id")
    vm.title = " "
    assertFalse(vm.canSave)
  }

  @Test
  fun edit_locationQueryChange_triggersSearch() = runTest {
    val repo = ToDoRepositoryLocal()
    val id = "todo-2"
    repo.add(
        ToDo(
            id = id,
            title = "Task",
            dueDate = LocalDate.now(),
            priority = Priority.MEDIUM,
            status = Status.TODO))

    val fakeLocationRepo =
        FakeLocationRepository().apply {
          searchResults =
              listOf(Location(46.52, 6.56, "Library"), Location(46.51, 6.55, "Cafeteria"))
        }
    val vm = EditToDoViewModel(repo, id, fakeLocationRepo)
    advanceUntilIdle()

    vm.onLocationQueryChange("Lib")
    advanceUntilIdle()

    assertEquals(1, vm.locationSuggestions.size)
    assertEquals("Library", vm.locationSuggestions[0].name)
  }

  @Test
  fun edit_locationSelected_updatesQueryAndClearsSuggestions() = runTest {
    val repo = ToDoRepositoryLocal()
    val id = "todo-3"
    repo.add(
        ToDo(
            id = id,
            title = "Task",
            dueDate = LocalDate.now(),
            priority = Priority.MEDIUM,
            status = Status.TODO))

    val fakeLocationRepo =
        FakeLocationRepository().apply { searchResults = listOf(Location(46.52, 6.56, "Gym")) }
    val vm = EditToDoViewModel(repo, id, fakeLocationRepo)
    advanceUntilIdle()

    vm.onLocationQueryChange("Gym")
    advanceUntilIdle()

    val selected = vm.locationSuggestions[0]
    vm.onLocationSelected(selected)

    assertEquals("Gym", vm.locationQuery)
    assertTrue(vm.locationSuggestions.isEmpty())
  }

  @Test
  fun edit_save_updatesLocationFromSelected() = runTest {
    val repo = ToDoRepositoryLocal()
    val id = "todo-4"
    repo.add(
        ToDo(
            id = id,
            title = "Meeting",
            dueDate = LocalDate.now(),
            priority = Priority.HIGH,
            status = Status.TODO,
            location = "Old Location"))

    val vm = EditToDoViewModel(repo, id)
    advanceUntilIdle()

    assertEquals("Old Location", vm.locationQuery)

    // Select new location
    vm.onLocationSelected(Location(46.52, 6.56, "New Office"))
    vm.save {}
    advanceUntilIdle()

    val updated = repo.getById(id)!!
    assertEquals("New Office", updated.location)
  }

  @Test
  fun edit_save_updatesLocationFromQueryString() = runTest {
    val repo = ToDoRepositoryLocal()
    val id = "todo-5"
    repo.add(
        ToDo(
            id = id,
            title = "Task",
            dueDate = LocalDate.now(),
            priority = Priority.MEDIUM,
            status = Status.TODO,
            location = "Old"))

    val vm = EditToDoViewModel(repo, id)
    advanceUntilIdle()

    // Change query without selecting from suggestions
    vm.onLocationQueryChange("Custom Place")
    advanceUntilIdle()

    vm.save {}
    advanceUntilIdle()

    val updated = repo.getById(id)!!
    assertEquals("Custom Place", updated.location)
  }

  @Test
  fun edit_locationSearch_handlesError() = runTest {
    val repo = ToDoRepositoryLocal()
    val id = "todo-6"
    repo.add(
        ToDo(
            id = id,
            title = "Task",
            dueDate = LocalDate.now(),
            priority = Priority.MEDIUM,
            status = Status.TODO))

    val fakeLocationRepo = FakeLocationRepository().apply { searchThrowsException = true }
    val vm = EditToDoViewModel(repo, id, fakeLocationRepo)
    advanceUntilIdle()

    vm.onLocationQueryChange("EPFL")
    advanceUntilIdle()

    // Should handle error gracefully with empty suggestions
    assertTrue(vm.locationSuggestions.isEmpty())
  }

  @Test
  fun edit_preservesOriginalLocation_whenNotModified() = runTest {
    val repo = ToDoRepositoryLocal()
    val id = "todo-7"
    val originalLocation = "Original Place"
    repo.add(
        ToDo(
            id = id,
            title = "Task",
            dueDate = LocalDate.now(),
            priority = Priority.MEDIUM,
            status = Status.TODO,
            location = originalLocation))

    val vm = EditToDoViewModel(repo, id)
    advanceUntilIdle()

    assertEquals(originalLocation, vm.locationQuery)

    // Save without changing location
    vm.title = "Updated Task"
    vm.save {}
    advanceUntilIdle()

    val updated = repo.getById(id)!!
    assertEquals(originalLocation, updated.location)
  }

  //  ==================== OverviewViewModel Tests ====================

  @Test
  fun overview_sorts_nonDone_first_then_by_dueDate_and_supports_cycle_and_delete() = runTest {
    val repo = ToDoRepositoryLocal()

    // Three items: ensure sorting (non-DONE first, then earliest date)
    val a =
        ToDo(
            id = "a",
            title = "a",
            dueDate = LocalDate.of(2025, 1, 10),
            priority = Priority.MEDIUM,
            status = Status.DONE)
    val b =
        ToDo(
            id = "b",
            title = "b",
            dueDate = LocalDate.of(2025, 1, 1),
            priority = Priority.MEDIUM,
            status = Status.TODO)
    val c =
        ToDo(
            id = "c",
            title = "c",
            dueDate = LocalDate.of(2025, 1, 2),
            priority = Priority.MEDIUM,
            status = Status.IN_PROGRESS)
    repo.add(a)
    repo.add(b)
    repo.add(c)

    val vm = OverviewViewModel(repo)
    advanceUntilIdle()

    val sortedIds = vm.uiState.first { it.items.isNotEmpty() }.items.map { it.id }
    assertEquals(listOf("b", "c", "a"), sortedIds)

    // Cycle status b: TODO -> IN_PROGRESS -> DONE -> TODO
    vm.cycleStatus("b")
    advanceUntilIdle()
    assertEquals(Status.IN_PROGRESS, repo.getById("b")!!.status)
    vm.cycleStatus("b")
    advanceUntilIdle()
    assertEquals(Status.DONE, repo.getById("b")!!.status)
    vm.cycleStatus("b")
    advanceUntilIdle()
    assertEquals(Status.TODO, repo.getById("b")!!.status)

    // Delete c
    vm.delete("c")
    advanceUntilIdle()
    assertNull(repo.getById("c"))
  }
}
