package com.android.sample

import android.app.Application
import android.content.Context

// The comments on this file have been generated by an LLM(ChatGPT)
class EduMonApp : Application() {

  override fun onCreate() {
    super.onCreate()

    // Store a global application context so components without direct access
    // to an Activity/Fragment (e.g., ToastNotifier) can still display Toasts safely.
    // Using the Application context prevents memory leaks.
    appContext = this
  }

  companion object {
    // Global Application context — required for places where we cannot pass
    // a UI context (such as inside singletons). Used mainly by ToastNotifier.
    lateinit var appContext: Context
      private set
  }
}
