@file:Suppress("DEPRECATION")

package com.android.sample.ui.gamification

import android.annotation.SuppressLint
import android.os.Handler
import android.os.Looper
import android.view.LayoutInflater
import android.widget.TextView
import android.widget.Toast
import com.android.sample.EduMonApp
import com.android.sample.R
import com.android.sample.ui.profile.LevelUpRewardUiEvent

// Some parts of this code have been generated by an AI (ChatGPT)
object ToastNotifier {

  // Ensures all toast operations run on the main UI thread
  private val mainHandler = Handler(Looper.getMainLooper())

  // --- Deduplication state to prevent repeated identical toasts ----
  private var lastLevelUpTime = 0L
  private var lastLevelUpLevel = -1
  private var lastStatGainTime = 0L
  private var lastStatGainMessage = ""
  private const val DEBOUNCE_MS = 2000L // Minimum time between identical messages

  /**
   * Builds a user-friendly message for level-up rewards:
   * - Level reached
   * - Coins granted
   * - Accessories granted
   */
  private fun buildRewardMessage(event: LevelUpRewardUiEvent.RewardsGranted): String {
    val s = event.summary
    return buildString {
      append("🎉 Level ${event.newLevel} reached!")
      if (s.coinsGranted > 0) append(" 💰 +${s.coinsGranted} coins")
      if (s.accessoryIdsGranted.isNotEmpty()) {
        append(" 🎁 ${s.accessoryIdsGranted.size} new item")
        if (s.accessoryIdsGranted.size > 1) append("s")
      }
    }
  }

  /**
   * Displays a custom toast when the user levels up. Uses debounce to avoid showing multiple
   * identical toasts caused by ViewModel duplicate emissions.
   */
  fun showLevelUpEvent(event: LevelUpRewardUiEvent.RewardsGranted) {
    val now = System.currentTimeMillis()

    // Reject duplicate level-up messages emitted too close together
    if (event.newLevel == lastLevelUpLevel && (now - lastLevelUpTime) < DEBOUNCE_MS) {
      return
    }

    lastLevelUpLevel = event.newLevel
    lastLevelUpTime = now

    val message = buildRewardMessage(event)
    mainHandler.post { showCustomToast(message) }
  }

  /**
   * Displays a toast for stat gains (points/coins) during normal gameplay. Also debounced to
   * prevent UI spam.
   */
  fun showStatGain(points: Int, coins: Int) {
    val msg =
        buildString {
              if (points > 0) append("✨ +$points pts")
              if (coins > 0) {
                if (points > 0) append("  ")
                append("💰 +$coins coins")
              }
            }
            .trim()

    if (msg.isBlank()) return

    val now = System.currentTimeMillis()

    // Reject duplicate stat-gain messages emitted too close together
    if (msg == lastStatGainMessage && (now - lastStatGainTime) < DEBOUNCE_MS) {
      return
    }

    lastStatGainMessage = msg
    lastStatGainTime = now

    mainHandler.post { showCustomToast(msg) }
  }

  /** Inflates and displays our app-themed custom toast layout. */
  @SuppressLint("InflateParams")
  private fun showCustomToast(message: String) {
    val ctx = EduMonApp.appContext
    val inflater = LayoutInflater.from(ctx)

    // Inflate custom toast layout
    val layout = inflater.inflate(R.layout.toast_custom, null)
    val text = layout.findViewById<TextView>(R.id.toast_text)
    text.text = message

    // Show the styled toast
    Toast(ctx).apply {
      duration = Toast.LENGTH_SHORT
      view = layout
      show()
    }
  }
}
